networks:
  eventstore-grafana-network:

volumes:
  eventstore-grafana-storage:
  eventstore-prometheus-storage:

services:
  prometheus:
    image: prom/prometheus:v2.45.6 # v2.38.0
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - eventstore-prometheus-storage:/prometheus
    ports:
      - 9090:9090
    networks:
      - eventstore-grafana-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:10.4.4 #9.1.3
    volumes:
      - ./config/grafana/etc-grafana-provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
      - eventstore-grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - eventstore-grafana-network
 
  otel-collector:
    image: otel/opentelemetry-collector:0.103.1 # 0.60.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./config/collector/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
    networks:
      - eventstore-grafana-network
