{
 "title": "Eventstore Panels",
 "description": "Series of panels displaying data for EventStore 23.6+",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Cache Hits/Misses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Hits/Misses",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 17, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "/s" } },
     "targets": [
      {
       "expr": "rate(eventstore_cache_hits_misses{instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{cache}} - {{kind}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Sizes (bytes mode)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "eventstore_cache_resources_bytes{instance=~\"$Instance\", kind=\"size\"}",
       "legendFormat": "{{instance}} - {{cache}}"
      }
     ]
    },
    {
     "title": "Entries",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "eventstore_cache_resources_entries{instance=~\"$Instance\", kind=\"count\"}",
       "legendFormat": "{{instance}} - {{cache}}"
      }
     ]
    },
    {
     "title": "Capacity (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "eventstore_cache_resources_bytes{instance=~\"$Instance\", kind=\"capacity\"}",
       "legendFormat": "{{instance}} - {{cache}}"
      }
     ]
    },
    {
     "title": "Utilization",
     "type": "timeseries",
     "description": "TODO double check this query",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "eventstore_cache_resources_bytes{instance=~\"$Instance\", kind=\"size\"} / ignoring(kind) eventstore_cache_resources_bytes{instance=~\"$Instance\", kind=\"capacity\"}",
       "legendFormat": "{{instance}} - {{cache}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "scalar(max(eventstore_checkpoints{name=\"writer\", read=\"non-flushed\"})) - eventstore_checkpoints{instance=~\"$Instance\", name=\"replication\", read=\"non-flushed\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Checkpoints",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "eventstore_checkpoints{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Events Served",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "event/s" } },
     "targets": [
      {
       "expr": "rate(eventstore_io_events{instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{activity}}"
      }
     ]
    },
    {
     "title": "Approx Events Sizes",
     "type": "timeseries",
     "description": "TODO consider if rate is the right function here",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "byte/event" } },
     "targets": [
      {
       "expr": "rate(eventstore_io_bytes{instance=~\"$Instance\", activity=\"read\"}[$__rate_interval]) / rate(eventstore_io_events{instance=~\"$Instance\", activity=\"read\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{activity}}"
      }
     ]
    },
    {
     "title": "Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(eventstore_io_bytes{instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{activity}}"
      },
      {
       "expr": "rate(eventstore_checkpoints{instance=~\"$Instance\", name=\"writer\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - written"
      }
     ]
    }
   ]
  },
  {
   "title": "Gossip",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sending Gossip (Success)",
     "type": "bargauge",
     "description": "Increase over the range",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (increase(eventstore_gossip_latency_seconds_bucket{instance=~\"$Instance\", activity=\"push-to-peer\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sending Gossip (Failed)",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (increase(eventstore_gossip_latency_seconds_bucket{instance=~\"$Instance\", activity=\"push-to-peer\", status=\"failed\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Gossip Send Latency",
     "type": "timeseries",
     "description": "TODO consider this carefully",
     "gridPos": { "h": 12, "w": 14, "x": 10, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(instance) (rate(eventstore_gossip_latency_seconds_sum{instance=~\"$Instance\", activity=\"push-to-peer\"}[$__rate_interval])) / sum by(instance) (rate(eventstore_gossip_latency_seconds_count{instance=~\"$Instance\", activity=\"push-to-peer\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Processing Gossip (Success)",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (increase(eventstore_gossip_processing_duration_seconds_bucket{instance=~\"$Instance\", status=\"successful\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Processing Gossip (Failed)",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (increase(eventstore_gossip_processing_duration_seconds_bucket{instance=~\"$Instance\", status=\"failed\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Incoming gRPC & Http",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "gRPC call rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(eventstore_incoming_grpc_calls{instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{kind}}"
      }
     ]
    },
    {
     "title": "Current gRPC calls",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "eventstore_current_incoming_grpc_calls{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Successful gRPC Reads",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (increase(eventstore_grpc_method_duration_seconds_bucket{activity=\"read\", status=\"successful\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Successful gRPC Appends",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 3, "x": 3, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (increase(eventstore_grpc_method_duration_seconds_bucket{instance=~\"$Instance\", activity=\"append\", status=\"successful\"}[$__range]))  ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Reads",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 3, "x": 6, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (increase(eventstore_grpc_method_duration_seconds_bucket{instance=~\"$Instance\", activity=\"read\", status=\"failed\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Appends",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 2, "x": 9, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (increase(eventstore_grpc_method_duration_seconds_bucket{instance=~\"$Instance\", activity=\"append\", status=\"failed\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Http Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "eventstore_kestrel_connections{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}} - {{kind}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Pauses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "eventstore_gc_pause_duration_max_seconds{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    }
   ]
  },
  { "title": "Process (TODO)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue Lengths",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "eventstore_queue_queueing_duration_max_seconds{instance=~\"$Instance\", range=\"16-20 seconds\"}",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    },
    {
     "title": "Thread Pool Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "eventstore_proc_thread_pool_pending_work_item_count{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    },
    {
     "title": "Messages processed by Queue",
     "type": "timeseries",
     "description": "Requires `Queues.Processing` to be enabled in the telemetry configuration. Not usually recommended.\n\nThis is counting how many messages are actually processed. It is not extrapolating from the time it takes to process a message.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(queue) (rate(eventstore_queue_processing_duration_seconds_count[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Message processed by Type",
     "type": "timeseries",
     "description": "Requires `Queues.Processing` to be enabled in the telemetry configuration. Not usually recommended.\n\nThis is counting how many messages are actually processed. It is not extrapolating from the time it takes to process a message.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(message_type) (rate(eventstore_queue_processing_duration_seconds_count{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Status Timelines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 14, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min by(instance) (eventstore_proc_up_time{instance=~\"$Instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Up",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "up{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Statuses",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "topk by(instance) (1, eventstore_statuses{name=\"Node\", instance=~\"$Instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scavenge",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "topk by(instance) (1, eventstore_statuses{name=\"Scavenge\", instance=~\"$Instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Index Merges",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "topk by(instance) (1, eventstore_statuses{name=\"Index\", instance=~\"$Instance\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Writer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Writer Flush Size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "eventstore_writer_flush_size_max{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Writer Flush Duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "eventstore_writer_flush_duration_max_seconds{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System (TODO)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sys - CPU",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "eventstore_sys_cpu{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}