{
 "title": "EventStore Summary - Preview",
 "description": "Summary of cluster status for EventStore 23.6+\r\n",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "$Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Instance" },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 1, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"$Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Summary",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk by(name) (1, eventstore_statuses{instance=~\"$Instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(max(eventstore_checkpoints{name=\"writer\", read=\"non-flushed\"})) - eventstore_checkpoints{instance=~\"$Instance\", name=\"replication\", read=\"non-flushed\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gRPC failed calls",
   "type": "gauge",
   "description": "TODO: take account of the current period",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(eventstore_incoming_grpc_calls{instance=~\"$Instance\", kind=~\"deadline-exceeded|failed|unimplemented\"})) / scalar(eventstore_incoming_grpc_calls{instance=~\"$Instance\", kind=\"total\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eventstore_sys_cpu{instance=~\"$Instance\"} / 100",
     "legendFormat": "CPU"
    },
    {
     "expr": "1 - (eventstore_sys_mem_bytes{instance=~\"$Instance\", kind=\"free\"} / scalar(eventstore_sys_mem_bytes{instance=~\"$Instance\", kind=\"total\"}))",
     "legendFormat": "Memory"
    },
    {
     "expr": "eventstore_sys_disk_bytes{instance=~\"$Instance\", kind=\"used\"} / scalar (eventstore_sys_disk_bytes{instance=~\"$Instance\", kind=\"total\"})",
     "legendFormat": "Disk {{disk}}"
    }
   ]
  },
  {
   "title": "Queue Busyness",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(eventstore_queue_busy_seconds{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Max Queuing Duration",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eventstore_queue_queueing_duration_max_seconds{instance=~\"$Instance\", range=\"16-20 seconds\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "GC Pauses",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eventstore_gc_pause_duration_max_seconds{instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Thread Pool Queue",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eventstore_proc_thread_pool_pending_work_item_count{instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(eventstore_disk_io_bytes{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{activity}}"
    }
   ]
  }
 ]
}