{
 "title": "KurrentDB Summary",
 "description": "Summary of cluster status for KurrentDB\r\n",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "$Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Instance" },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 9, "w": 1, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"$Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Summary",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk by(name) (1, kurrentdb_statuses{instance=~\"$Instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "gauge",
   "description": "LIMITATION: This will show incorrect (far too high) values if nodes from multiple clusters are exporting metrics to the same datasource",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(max(kurrentdb_checkpoints{name=\"writer\", read=\"non-flushed\"})) - kurrentdb_checkpoints{instance=~\"$Instance\", name=\"replication\", read=\"non-flushed\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gRPC failed calls",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(kurrentdb_incoming_grpc_calls_total{instance=~\"$Instance\", kind=~\"deadline-exceeded|failed|unimplemented\"}[$__rate_interval]))) / scalar(rate(kurrentdb_incoming_grpc_calls_total{instance=~\"$Instance\", kind=\"total\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kurrentdb_sys_cpu{instance=~\"$Instance\"} / 100",
     "legendFormat": "CPU"
    },
    {
     "expr": "1 - (kurrentdb_sys_mem_bytes{instance=~\"$Instance\", kind=\"free\"} / scalar(kurrentdb_sys_mem_bytes{instance=~\"$Instance\", kind=\"total\"}))",
     "legendFormat": "Memory"
    },
    {
     "expr": "kurrentdb_sys_disk_bytes{instance=~\"$Instance\", kind=\"used\"} / scalar (kurrentdb_sys_disk_bytes{instance=~\"$Instance\", kind=\"total\"})",
     "legendFormat": "Disk {{disk}}"
    }
   ]
  },
  {
   "title": "Events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(kurrentdb_io_events_total{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{activity}}"
    }
   ]
  },
  {
   "title": "Max Queuing Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kurrentdb_queue_queueing_duration_max_seconds{instance=~\"$Instance\", range=\"16-20 seconds\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "GC Pauses",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kurrentdb_gc_pause_duration_max_seconds{instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Thread Pool Queue",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kurrentdb_proc_thread_pool_pending_work_item_count{instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(kurrentdb_disk_io_bytes_total{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{activity}}"
    }
   ]
  }
 ]
}