{
 "title": "KurrentDB Panels",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Cache Hits/Misses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Hits/Misses",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 17, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "/s" } },
     "targets": [
      {
       "expr": "rate(kurrentdb_cache_hits_misses_total{instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{cache}} - {{kind}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Sizes (bytes mode)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "kurrentdb_cache_resources_bytes{instance=~\"$Instance\", kind=\"size\"}",
       "legendFormat": "{{instance}} - {{cache}}"
      }
     ]
    },
    {
     "title": "Entries",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kurrentdb_cache_resources_entries{instance=~\"$Instance\", kind=\"count\"}",
       "legendFormat": "{{instance}} - {{cache}}"
      }
     ]
    },
    {
     "title": "Capacity (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "kurrentdb_cache_resources_bytes{instance=~\"$Instance\", kind=\"capacity\"}",
       "legendFormat": "{{instance}} - {{cache}}"
      }
     ]
    },
    {
     "title": "Utilization",
     "type": "timeseries",
     "description": "TODO double check this query",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "kurrentdb_cache_resources_bytes{instance=~\"$Instance\", kind=\"size\"} / ignoring(kind) kurrentdb_cache_resources_bytes{instance=~\"$Instance\", kind=\"capacity\"}",
       "legendFormat": "{{instance}} - {{cache}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 603 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "scalar(max(kurrentdb_checkpoints{name=\"writer\", read=\"non-flushed\"})) - kurrentdb_checkpoints{instance=~\"$Instance\", name=\"replication\", read=\"non-flushed\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Checkpoints",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 611 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "kurrentdb_checkpoints{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connectors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Connector Count",
     "type": "timeseries",
     "description": "Current number of active data connectors",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(instance, connector_type) (kurrent_connector_active{instance=~\"$Instance\"})",
       "legendFormat": "{{instance}} - {{connector_type}}"
      }
     ]
    },
    {
     "title": "Processor Errors",
     "type": "timeseries",
     "description": "Rate of errors encountered during message processing",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "recps" } },
     "targets": [
      {
       "expr": "sum by(instance, messaging_kurrent_processor_client_id) (rate(messaging_kurrent_processor_error_count_total{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} - {{messaging_kurrent_processor_client_id}}"
      }
     ]
    },
    {
     "title": "Consumer Lag",
     "type": "timeseries",
     "description": "Difference between the latest message and the last consumed message",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(instance, messaging_kurrent_consumer_client_id) (messaging_kurrent_consumer_lag{instance=~\"$Instance\"})",
       "legendFormat": "{{instance}} - {{messaging_kurrent_consumer_client_id}}"
      }
     ]
    },
    {
     "title": "Producer Queue Length",
     "type": "timeseries",
     "description": "Current number of messages waiting in the producer queue",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(instance, messaging_kurrent_producer_client_id) (messaging_kurrent_producer_queue_length{instance=~\"$Instance\"})",
       "legendFormat": "{{instance}} - {{messaging_kurrent_producer_client_id}}"
      }
     ]
    },
    {
     "title": "Messages Consumed",
     "type": "timeseries",
     "description": "Rate of messages consumed from the messaging system",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "recps" } },
     "targets": [
      {
       "expr": "sum by(instance, messaging_kurrent_consumer_client_id) (rate(messaging_kurrent_consumer_message_count_total{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} - {{messaging_kurrent_consumer_client_id}}"
      }
     ]
    },
    {
     "title": "Messages Produced",
     "type": "timeseries",
     "description": "Rate of messages successfully produced to the messaging system",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "recps" } },
     "targets": [
      {
       "expr": "sum by(instance, messaging_kurrent_producer_client_id) (rate(messaging_kurrent_producer_message_count_total{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} - {{messaging_kurrent_producer_client_id}}"
      }
     ]
    },
    {
     "title": "Consumer Mean Commit Latency",
     "type": "timeseries",
     "description": "Mean latency observed when committing message offsets",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(instance, messaging_kurrent_consumer_client_id) (rate(messaging_kurrent_consumer_commit_latency_sum{instance=~\"$Instance\"}[$__rate_interval]))\r\n/\r\nsum by(instance, messaging_kurrent_consumer_client_id) (rate(messaging_kurrent_consumer_commit_latency_count{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} - {{messaging_kurrent_consumer_client_id}}"
      }
     ]
    },
    {
     "title": "Producer Mean Time Per Message",
     "type": "timeseries",
     "description": "Mean time taken to produce messages to the messaging system\n\nNote: at time of writing, the unit of this metric is seconds, not milliseconds as indicated in the name. The graph shows measurements in the correct unit.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(instance, messaging_kurrent_producer_client_id) (rate(messaging_kurrent_producer_produce_duration_milliseconds_sum{instance=~\"$Instance\"}[$__rate_interval]))\r\n/\r\nsum by(instance, messaging_kurrent_producer_client_id) (rate(messaging_kurrent_producer_produce_duration_milliseconds_count{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} - {{messaging_kurrent_producer_client_id}}"
      }
     ]
    },
    {
     "title": "Sink Written Records",
     "type": "timeseries",
     "description": "Rate of records successfully written to the sink",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "recps" } },
     "targets": [
      {
       "expr": "sum by(instance, connector_id) (rate(kurrent_sink_written_records_sum{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} - {{connector_id}}"
      }
     ]
    },
    {
     "title": "Sink Errors",
     "type": "timeseries",
     "description": "Rate of errors encountered during sink operations",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(instance, messaging_kurrent_processor_client_id) (rate(messaging_kurrent_processor_error_count_total{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} - {{messaging_kurrent_processor_client_id}}"
      }
     ]
    },
    {
     "title": "Mean Sink Transform Duration",
     "type": "timeseries",
     "description": "Duration of data transformation before writing to the sink",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by(instance, connector_id) (rate(kurrent_sink_transform_duration_milliseconds_sum{instance=~\"$Instance\"}[$__rate_interval]))\r\n/\r\nsum by(instance, connector_id) (rate(kurrent_sink_transform_duration_milliseconds_count{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} - {{connector_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Events Served",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "event/s" } },
     "targets": [
      {
       "expr": "rate(kurrentdb_io_events_total{instance=~\"$Instance\", activity=\"read\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Events Written",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "event/s" } },
     "targets": [
      {
       "expr": "rate(kurrentdb_io_events_total{instance=~\"$Instance\", activity=\"written\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Event Bytes Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(kurrentdb_io_bytes_total{instance=~\"$Instance\", activity=\"read\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Bytes Written",
     "type": "timeseries",
     "description": "Measures movement of the writer checkpoint",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(kurrentdb_checkpoints{instance=~\"$Instance\", name=\"writer\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Chunk Read Distribution",
     "type": "bargauge",
     "description": "0 is the Current chunk. 1 is the prevous chunk etc.\nVisualizes where data is being read from in the log relative to the tail. Helps to set ChunkCache size and Archive retention policy.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "recps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (rate(kurrentdb_logical_chunk_read_distribution_bucket{instance=~\"$Instance\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Approx Events Sizes",
     "type": "timeseries",
     "description": "TODO consider if rate is the right function here",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "byte/event" } },
     "targets": [
      {
       "expr": "rate(kurrentdb_io_bytes_total{instance=~\"$Instance\", activity=\"read\"}[$__rate_interval]) / rate(kurrentdb_io_events_total{instance=~\"$Instance\", activity=\"read\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{activity}}"
      }
     ]
    },
    {
     "title": "Record Reads from Chunk Cache",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "recps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (rate(kurrentdb_io_record_read_duration_seconds_bucket{instance=~\"$Instance\", source=\"ChunkCache\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Record Reads from File System",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "recps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (rate(kurrentdb_io_record_read_duration_seconds_bucket{instance=~\"$Instance\", source=\"FileSystem\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Record Reads from Archive",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "recps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (rate(kurrentdb_io_record_read_duration_seconds_bucket{instance=~\"$Instance\", source=\"Archive\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Gossip",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sending Gossip (Success)",
     "type": "bargauge",
     "description": "Increase over the range",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (increase(kurrentdb_gossip_latency_seconds_bucket{instance=~\"$Instance\", activity=\"push-to-peer\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sending Gossip (Failed)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (increase(kurrentdb_gossip_latency_seconds_bucket{instance=~\"$Instance\", activity=\"push-to-peer\", status=\"failed\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Gossip Send Latency",
     "type": "timeseries",
     "description": "TODO consider this carefully",
     "gridPos": { "h": 16, "w": 12, "x": 10, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(instance) (rate(kurrentdb_gossip_latency_seconds_sum{instance=~\"$Instance\", activity=\"push-to-peer\"}[$__rate_interval])) / sum by(instance) (rate(kurrentdb_gossip_latency_seconds_count{instance=~\"$Instance\", activity=\"push-to-peer\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Processing Gossip (Success)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (increase(kurrentdb_gossip_processing_duration_seconds_bucket{instance=~\"$Instance\", status=\"successful\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Processing Gossip (Failed)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (increase(kurrentdb_gossip_processing_duration_seconds_bucket{instance=~\"$Instance\", status=\"failed\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Incoming gRPC & Http",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "gRPC call rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1637 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(kurrentdb_incoming_grpc_calls_total{instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{kind}}"
      }
     ]
    },
    {
     "title": "Current gRPC calls",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 1637 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kurrentdb_current_incoming_grpc_calls{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Successful gRPC Reads",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1842 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (increase(kurrentdb_grpc_method_duration_seconds_bucket{instance=~\"$Instance\", activity=\"read\", status=\"successful\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Successful gRPC Appends",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1842 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (increase(kurrentdb_grpc_method_duration_seconds_bucket{instance=~\"$Instance\", activity=\"append\", status=\"successful\"}[$__range]))  ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Reads",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1842 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (increase(kurrentdb_grpc_method_duration_seconds_bucket{instance=~\"$Instance\", activity=\"read\", status=\"failed\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Appends",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 2, "x": 9, "y": 1842 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (increase(kurrentdb_grpc_method_duration_seconds_bucket{instance=~\"$Instance\", activity=\"append\", status=\"failed\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Http Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 1842 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kurrentdb_kestrel_connections{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}} - {{kind}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Pauses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1058 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kurrentdb_gc_pause_duration_max_seconds{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    },
    {
     "title": "GC Collection Counts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1058 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(kurrentdb_gc_collection_count_total{instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{generation}}"
      }
     ]
    },
    {
     "title": "Time In GC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1058 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "kurrentdb_gc_time_in_gc{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC Generation Sizes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1066 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "kurrentdb_gc_generation_size_bytes{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}} - {{generation}}"
      }
     ]
    },
    {
     "title": "Allocation Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1066 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(kurrentdb_gc_allocated_bytes_total{instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Persistent Subscriptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processing Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 3046 },
     "fieldConfig": { "defaults": { "unit": "event/s" } },
     "targets": [
      {
       "expr": "sum by(instance,event_stream_id,group_name) (rate(kurrentdb_persistent_sub_items_processed_total{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} - {{event_stream_id}}/{{group_name}}"
      }
     ]
    },
    {
     "title": "In Flight Messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 3046 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kurrentdb_persistent_sub_in_flight_messages{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}} - {{event_stream_id}}/{{group_name}}"
      }
     ]
    },
    {
     "title": "Connection count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 3054 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kurrentdb_persistent_sub_connections{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}} - {{event_stream_id}}/{{group_name}}"
      }
     ]
    },
    {
     "title": "Lag",
     "type": "timeseries",
     "description": "Streams other than $all only",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 3054 },
     "fieldConfig": { "defaults": { "unit": "event" } },
     "targets": [
      {
       "expr": "sum by(instance,event_stream_id,group_name) (kurrentdb_persistent_sub_last_known_event_number{instance=~\"$Instance\"}) - sum by(instance,event_stream_id,group_name) (kurrentdb_persistent_sub_checkpointed_event_number{instance=~\"$Instance\"})",
       "legendFormat": "{{instance}} - {{event_stream_id}}/{{group_name}}"
      }
     ]
    },
    {
     "title": "Parked Message Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 3062 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kurrentdb_persistent_sub_parked_messages{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}} - {{event_stream_id}}/{{group_name}}"
      }
     ]
    },
    {
     "title": "Oldest Parked Message",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 3062 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kurrentdb_persistent_sub_oldest_parked_message_seconds{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}} - {{event_stream_id}}/{{group_name}}"
      }
     ]
    },
    {
     "title": "Park Message Requests Rate",
     "type": "timeseries",
     "description": "The rate at which messages are being parked. Includes the reason (explicit nak from client vs max retry limit reached by the server).\n\nv25.0.1+",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 3090 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "rate(kurrentdb_persistent_sub_park_message_requests{instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{event_stream_id}}/{{group_name}} - {{reason}}"
      }
     ]
    },
    {
     "title": "Parked Message Replay Requests",
     "type": "timeseries",
     "description": "Count of parked message replay requests.\n\nv25.0.1+",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 3090 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kurrentdb_persistent_sub_parked_message_replays{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}} - {{event_stream_id}}/{{group_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 763 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "kurrentdb_sys_cpu{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Thread Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 763 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kurrentdb_proc_thread_count{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 773 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kurrentdb_sys_mem_bytes{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}} - {{kind}}"
      },
      {
       "expr": "kurrentdb_proc_mem_bytes{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}} - {{kind}}"
      },
      {
       "expr": "kurrentdb_gc_generation_size_bytes{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}} - {{generation}}"
      }
     ]
    },
    {
     "title": "Disk Utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 773 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kurrentdb_sys_disk_bytes{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}} - {{disk}} - {{kind}}"
      }
     ]
    },
    {
     "title": "Disk IO Bytes ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 783 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(kurrentdb_disk_io_bytes_total{instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{activity}}"
      }
     ]
    },
    {
     "title": "Disk IO Operations (OS Level)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 783 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(kurrentdb_disk_io_operations_total{instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{activity}}"
      }
     ]
    },
    {
     "title": "Up Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 793 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kurrentdb_proc_up_time_seconds_total{instance=~\"$Instance\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Projections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Projection progress",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1657 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(kurrentdb_projection_progress{instance=~\"$Instance\"}) by (instance,projection)",
       "legendFormat": "{{instance}} - {{projection}}"
      }
     ]
    },
    {
     "title": "Projection events per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 1657 },
     "fieldConfig": { "defaults": { "unit": "event/s" } },
     "targets": [
      {
       "expr": "sum by(instance,projection) (rate(kurrentdb_projection_events_processed_after_restart_total{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} - {{projection}}"
      }
     ]
    },
    {
     "title": "Projection Status",
     "type": "table",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1715 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(projection, instance) (kurrentdb_projection_running{instance=~\"$Instance\"})",
       "legendFormat": "{{instance}} - {{projection}}"
      }
     ]
    },
    {
     "title": "Max Recent State Serialization Duration",
     "type": "timeseries",
     "description": "Per event\n\nv25.1+\n",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 1715 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kurrentdb_projection_state_serialization_duration_max_seconds{instance=~\"$Instance\", range=\"16-20 seconds\"}",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    },
    {
     "title": "Example: Execution duration distribution of \"my-projection\": \"$any\" function",
     "type": "bargauge",
     "description": "25.1+",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1724 },
     "fieldConfig": { "defaults": { "unit": "events" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (increase(kurrentdb_projection_execution_duration_seconds_bucket{instance=~\"$Instance\", projection=\"my-projection\", jsFunction=\"$any\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max Recent Execution Duration",
     "type": "timeseries",
     "description": "Per event\n\nv25.1+\n",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 1724 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kurrentdb_projection_execution_duration_max_seconds{instance=~\"$Instance\", range=\"16-20 seconds\"}",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    },
    {
     "title": "Large Projection States",
     "type": "timeseries",
     "description": "25.1+\nOnly projection states that are >= 60% of MaxProjectionStateSize are shown.",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1733 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kurrentdb_projection_state_size{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}} - {{projection}} - {{partition}}"
      },
      {
       "expr": "kurrentdb_projection_state_size_bound{instance!~\"$Instance\"}",
       "legendFormat": "{{bound}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue Lengths",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kurrentdb_queue_queueing_duration_max_seconds{instance=~\"$Instance\", range=\"16-20 seconds\"}",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    },
    {
     "title": "Thread Pool Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kurrentdb_proc_thread_pool_pending_work_item_count{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}} - {{name}}"
      }
     ]
    },
    {
     "title": "Queue Busyness",
     "type": "timeseries",
     "description": "% of the time that the queue is actively processing messages.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(kurrentdb_queue_busy_seconds_total{instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{queue}}"
      }
     ]
    },
    {
     "title": "Message processed by Type",
     "type": "timeseries",
     "description": "Requires `Queues.Processing` to be enabled in the telemetry configuration. Not usually recommended.\n\nThis is counting how many messages are actually processed. It is not extrapolating from the time it takes to process a message.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(message_type) (rate(kurrentdb_queue_processing_duration_seconds_count{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Messages processed by Queue",
     "type": "timeseries",
     "description": "Requires `Queues.Processing` to be enabled in the telemetry configuration. Not usually recommended.\n\nThis is counting how many messages are actually processed. It is not extrapolating from the time it takes to process a message.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(queue, instance) (rate(kurrentdb_queue_processing_duration_seconds_count{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} - {{queue}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Status Timelines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 14, "x": 0, "y": 1079 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min by(instance) (kurrentdb_proc_up_time_seconds_total{instance=~\"$Instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Up",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 1094 },
     "targets": [
      {
       "expr": "up{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Statuses",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 1100 },
     "targets": [
      {
       "expr": "topk by(instance) (1, kurrentdb_statuses{name=\"Node\", instance=~\"$Instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scavenge",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 1106 },
     "targets": [
      {
       "expr": "topk by(instance) (1, kurrentdb_statuses{name=\"Scavenge\", instance=~\"$Instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Index Merges",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 1112 },
     "targets": [
      {
       "expr": "topk by(instance) (1, kurrentdb_statuses{name=\"Index\", instance=~\"$Instance\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Writer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Writer Flush Size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3223 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "kurrentdb_writer_flush_size_max{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Writer Flush Duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3223 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kurrentdb_writer_flush_duration_max_seconds{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}